title: "[component]: "
labels: [ "Component Request" ]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for suggesting a new component!  
        Before submitting, please check existing open and closed requests to see if a similar component has already been proposed.

  - type: textarea
    id: component-description
    attributes:
      label: Component Description
      description: Provide a detailed explanation of the component you are requesting.
      placeholder: "A card component for displaying product details with an image, title, and price..."
    validations:
      required: true

  - type: input
    id: reference-url
    attributes:
      label: Example or Reference
      description: If available, provide a link to an example or relevant documentation.
      placeholder: ex. https://example.com
    validations:
      required: false
